### ISSUE TITLE
Unsigned Assembly

### ISSUE THREAD

**Issue by SinghManvir** [mirajavora/sendgrid-webhooks#20]
Can you please release a signed version of the assembly?

**Comment by mirajavora** [comment]
Hey @SinghManvir, yeah, that should be no problem. Let me have a look at that later on this week and release a new nuget package ;-)

Thanks,
Mira

**Comment by tgardner** [comment]
Hi @mirajavora,
Any update on this?

Thanks,
Trent

**Comment by mirajavora** [comment]
Hi @tgardner, @SinghManvir,

I've released a strongly signed assembly earlier today and you should be able to pull it down after the indexing has completed.

https://www.nuget.org/packages/Sendgrid.Webhooks/1.2.1

Let me know if there's anything else :-)

Thanks,
Mira

**Comment by SinghManvir** [comment]
Thanks a lot, @mirajavora.
