### ISSUE TITLE
Upgrade to SendGrid v3 Web API

### ISSUE THREAD

**Issue by thinkingserious** [mirajavora/sendgrid-webhooks#21]
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/how_to_migrate_from_v2_to_v3_mail_send.html
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Thanks!

**Comment by mirajavora** [comment]
Hey @thinkingserious,

Do these changes also apply to webhooks? The api details relate to send mail API rather than to the webhooks. To my knowledge we're already on the v3 api for webhooks.

Do you have any other details of required changes for this project?

Thanks,
Mira

**Comment by thinkingserious** [comment]
Apologies, there are no updates necessary since this library only covers the webhooks. Thanks!
