### ISSUE TITLE
Exception when receiving Processed event

### ISSUE THREAD

**Issue by salomongorin** [mirajavora/sendgrid-webhooks#22]
Hi,

We've noticed an issue when receiving the Processed event when we upgraded from version 1.0.1

The JSON being sent by SendGrid contains a floating point number in the "send_at" field of the Processed event. In version 1.0.1 this was dealt with correctly, but in this current version an exception is thrown when trying to cast the vale as long. Converting the value to a long in the JSON by eliminating the decimal allows the code to run correctly.

Not sure if this is malformed JSON coming in from SendGrid or a bug in this code or both.

**Comment by mirajavora** [comment]
Hi @salomongorin,

Thanks for raising this. It's possible the code incorrectly assumes long rather than float for the send_at parameter. I'll see what I can dig out of the Sendgrid docs and look into fixing this.

Thanks,
Mira

**Comment by SimonLuckenuik** [comment]
FYI, used Convert.ToDouble that should support both the double and long cases correctly.

**Comment by maldworth** [comment]
Can this update please be published to nuget?

**Comment by mirajavora** [comment]
The fix has been included in the latest nuget release https://www.nuget.org/packages/Sendgrid.Webhooks/1.2.2

Give me a shout if there are any issues.
