### ISSUE TITLE
Migration to .NET Core

### ISSUE THREAD

**Issue by mglace** [mirajavora/sendgrid-webhooks#28]
I want to port this library to .NET Core.  Is anyone already working on doing this?   Should I perform a pull request or start a new repository?

**Comment by mirajavora** [comment]
Hey @mglace,

I'm not aware of anyone else working on this at the moment. Feel free to create a pull request and I can merge this and release as a new major version.

Thanks,
Mira

**Comment by kinetiq** [comment]
Yeah, this would be much appreciated. The pull request seems to exist.

**Comment by mirajavora** [comment]
Latest version 2.0.0 pushed out to nuget - contains changes in #34 - netstandard support!
