### ISSUE TITLE
NuGet release?

### ISSUE THREAD

**Issue by kinetiq** [mirajavora/sendgrid-webhooks#30]
I see that the repo has had MessageId and EventId for a few months, but it's not in the 1.2.2 release... Any chance you could do a release so I can make sure my messages are in order? Thanks for the library!

**Comment by daggmano** [comment]
*BUMP*

**Comment by kinetiq** [comment]
Has this repo been abandoned?  @mirajavora

**Comment by mirajavora** [comment]
Hey @kinetiq, looking at it now - I'll get that pushed out!

**Comment by kinetiq** [comment]
Yay! :)

**Comment by mirajavora** [comment]
Version 2.0.0 nuget package has been pushed out post #34 merge. Thanks everyone and sorry for taking some time!

**Comment by kinetiq** [comment]
Amazing! Thanks man!
